<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RFScout.Core\RFScout.Core.csproj" />
    <ProjectReference Include="..\RFScout.Infrastructure\RFScout.Infrastructure.csproj" />
    <ProjectReference Include="..\RFScout.Infrastructure.Linux\RFScout.Infrastructure.Linux.csproj" />
    <ProjectReference Include="..\RFScout.Infrastructure.Windows\RFScout.Infrastructure.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <ProjectReference Include="..\RFScout.Infrastructure.Linux\RFScout.Infrastructure.Linux.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <ProjectReference Include="..\RFScout.Infrastructure.Windows\RFScout.Infrastructure.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
  </ItemGroup>
</Project>
