<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework Condition="$([MSBuild]::IsOSPlatform('Windows'))">net9.0-windows10.0.19041.0</TargetFramework>
    <TargetFramework Condition="!$([MSBuild]::IsOSPlatform('Windows'))">net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <Compile Remove="**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RFScout.Infrastructure\RFScout.Infrastructure.csproj" />
  </ItemGroup>

</Project>
